blank_issues_enabled: false
contact_links:
  - name: 🤔 Questions, General Support, and Help
    url: https://github.com/withcatai/node-llama-cpp/discussions
    about: This issue tracker is not for support questions. Please use GitHub discussions instead.
