name: ✨ Feature request
description: Suggest an new idea for this project
labels:
  - requires triage
  - new feature
body:
  - type: markdown
    attributes:
      value: >-
        Have a question? This is the `node-llama-cpp` issue tracker – and is not the right place for general support or questions.
        Instead, use [`node-llama-cpp` GitHub Discussions](https://github.com/withcatai/node-llama-cpp/discussions) to get support or ask questions.
  - type: textarea
    id: problem
    attributes:
      label: Feature Description
      description: >-
        A clear and concise description of what the problem is,
        and why it needs to be implemented as a new feature in `node-llama-cpp`.
      placeholder: For example, "I'm frustrated when ..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: The Solution
      description: A clear and concise description of what you want to happen.
      placeholder: >-
        How can the requested feature be used to approach the problem it's supposed to solve?
    validations:
      required: true
  - type: textarea
    id: alt
    attributes:
      label: Considered Alternatives
      description: >-
        A clear and concise description of any alternative solutions or features you've considered.
      placeholder: If any workaround exists to the best of your knowledge, include it here.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here
  - type: checkboxes
    id: features
    attributes:
      label: Related Features to This Feature Request
      options:
        - label: Metal support
          required: false
        - label: CUDA support
          required: false
        - label: Vulkan support
          required: false
        - label: Grammar
          required: false
        - label: Function calling
          required: false
  - type: dropdown
    id: pr
    attributes:
      label: Are you willing to resolve this issue by submitting a Pull Request?
      options:
        - Yes, I have the time, and I know how to start.
        - >-
          Yes, I have the time, but I don't know how to start. I would need
          guidance.
        - >-
          No, I don’t have the time, but I can support (using donations)
          development.
        - >-
          No, I don’t have the time and I’m okay to wait for the community /
          maintainers to resolve this issue.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |-
        First-time contributors are always welcome! 🙌

        👋 Have a great day and thank you for the feature request!
