import {acquireLock, withLock} from "lifecycle-utils";
import bytes from "bytes";
import {Llama} from "../../bindings/Llama.js";
import {LlamaLocks, LlamaLogLevel} from "../../bindings/types.js";
import {getLlamaWithoutBackend} from "../../bindings/utils/getLlamaWithoutBackend.js";
import {getDefaultContextBatchSize, getDefaultContextSequences} from "../../evaluator/LlamaContext/LlamaContext.js";
import {GgufFileInfo} from "../types/GgufFileInfoTypes.js";
import {GgmlType, GgufTensorInfo} from "../types/GgufTensorInfoTypes.js";
import {GgufArchitectureType} from "../types/GgufMetadataTypes.js";
import {getReadablePath} from "../../cli/utils/getReadablePath.js";
import {padSafeContextSize} from "../../evaluator/LlamaContext/utils/padSafeContextSize.js";
import {removeNullFields, removeUndefinedFields} from "../../utils/removeNullFields.js";
import {LruCache} from "../../utils/LruCache.js";
import {GgufInsightsConfigurationResolver} from "./GgufInsightsConfigurationResolver.js";
import {GgufInsightsTokens} from "./GgufInsightsTokens.js";
import type {Promisable} from "../../utils/transformPromisable.js";
import type {LlamaContextOptions} from "../../evaluator/LlamaContext/types.js";
import type {AddonContextParams, AddonGgufMetadata, AddonModel, AddonModelParams} from "../../bindings/AddonTypes.js";

export type GgufInsightsResourceRequirements = {
    cpuRam: number,
    gpuVram: number
};

export class GgufInsights {
    /** @internal */ public readonly _llama: Llama;
    /** @internal */ private readonly _modelSize: number;
    /** @internal */ private _totalFileLayers: number | null = null;
    /** @internal */ private _supportsRanking?: boolean;
    /** @internal */ private _dominantTensorType?: GgmlType;
    /** @internal */ private _addonMetadata?: AddonGgufMetadata;
    /** @internal */ public _defaultUseMmap?: boolean;
    /** @internal */ public readonly _ggufFileInfo: GgufFileInfo;
    /** @internal */ private readonly _configurationResolver: GgufInsightsConfigurationResolver;
    /** @internal */ private readonly _tokens: GgufInsightsTokens;
    /** @internal */ private readonly _exactModelResourceRequirementsCache = new LruCache<string, GgufInsightsResourceRequirements>(40);
    /** @internal */ private readonly _exactContextResourceRequirementsCache = new LruCache<string, GgufInsightsResourceRequirements>(40);
    /** @internal */ private readonly _simulationSession: GgufInsightsSimulatorSession;
    /** @internal */ private readonly _locks = {};

    private constructor(ggufFileInfo: GgufFileInfo, llama: Llama) {
        this._llama = llama;
        this._ggufFileInfo = ggufFileInfo;

        this._modelSize = calculateTensorsSize(ggufFileInfo.fullTensorInfo ?? [], llama, true, true);
        this._configurationResolver = GgufInsightsConfigurationResolver._create(this);
        this._tokens = GgufInsightsTokens._create(this);
        this._simulationSession = this._createSimulatorSession();
    }

    /**
     * Get warnings about the model file that would affect its usage.
     *
     * Most of these warnings are also generated by `llama.cpp`
     */
    public getWarnings(modelFilePath?: string) {
        const warnings: string[] = [];
        const resolvedModelFilePath = modelFilePath || (
            this._ggufFileInfo.source?.type === "path"
                ? this._ggufFileInfo.source.path
                : undefined
        );
        const modelFileSourceText = (resolvedModelFilePath != null && resolvedModelFilePath !== "")
            ? ` ("${getReadablePath(resolvedModelFilePath)}")`
            : this._ggufFileInfo.source?.type === "uri"
                ? ` ("${getReadablePath(this._ggufFileInfo.source.uri)}")`
                : "";

        if (this._ggufFileInfo?.metadata?.tokenizer?.ggml?.model === "gpt2" &&
            this._ggufFileInfo?.metadata?.tokenizer?.ggml?.model == null
        ) {
            // equivalent to the warning in `llama.cpp` under `llm_load_vocab`: "missing pre-tokenizer type, using: 'default'"
            warnings.push(
                `This model file${modelFileSourceText} is missing a pre-tokenizer configuration. ` +
                "This may cause incorrect tokenization and thus degrade the generation quality. " +
                "Consider using a newer model or regenerating this GGUF model file"
            );
        }

        return warnings;
    }

    public get ggufFileInfo(): GgufFileInfo {
        return this._ggufFileInfo;
    }

    public get configurationResolver() {
        return this._configurationResolver;
    }

    public get tokens() {
        return this._tokens;
    }

    /** The context size the model was trained on */
    public get trainContextSize() {
        return this._ggufFileInfo.architectureMetadata.context_length;
    }

    /** The size of an embedding vector the model can produce */
    public get embeddingVectorSize() {
        return this._ggufFileInfo.architectureMetadata.embedding_length;
    }

    public get totalLayers() {
        const outputLayers = 1;
        return this._getTotalFileLayers() + outputLayers;
    }

    public get modelSize() {
        return this._modelSize;
    }

    public get flashAttentionSupported() {
        // source: `llama_new_context_with_model` in `llama.cpp`

        if (this._ggufFileInfo.metadata?.general?.architecture === GgufArchitectureType.grok)
            return false;
        else if (this._ggufFileInfo.metadata?.general?.architecture === GgufArchitectureType.gemma2)
            return false;
        else {
            const nHead = this._ggufFileInfo.architectureMetadata?.attention?.head_count ?? 0;
            const nEmbd = this._ggufFileInfo.architectureMetadata?.embedding_length ?? 0;
            const nEmbdHeadK = this._ggufFileInfo.architectureMetadata?.attention?.key_length ?? ((nHead == 0) ? 0 : (nEmbd / nHead));
            const nEmbdHeadV = this._ggufFileInfo.architectureMetadata?.attention?.value_length ?? ((nHead == 0) ? 0 : nEmbd / nHead);

            if (nEmbdHeadK !== nEmbdHeadV)
                return false;
        }

        return true;
    }

    public get hasEncoder() {
        switch (this._ggufFileInfo.metadata?.general?.architecture) {
            case GgufArchitectureType.t5:
            case GgufArchitectureType.t5encoder:
                return true;
        }

        return false;
    }

    public get hasDecoder() {
        switch (this._ggufFileInfo.metadata?.general?.architecture) {
            case GgufArchitectureType.t5encoder:
                return false;
        }

        return true;
    }

    public get isRecurrent() {
        // source: `llm_arch_is_recurrent` in `llama-arch.cpp`
        switch (this._ggufFileInfo.metadata?.general?.architecture) {
            case GgufArchitectureType.mamba:
            case GgufArchitectureType.mamba2:
            case GgufArchitectureType.rwkv6:
            case GgufArchitectureType.rwkv6qwen2:
            case GgufArchitectureType.rwkv7:
            case GgufArchitectureType.arwkv7:
                return true;
        }

        return false;
    }

    public get isHybrid() {
        // source: `llm_arch_is_hybrid` in `llama-arch.cpp`
        switch (this._ggufFileInfo.metadata?.general?.architecture) {
            case GgufArchitectureType.jamba:
            case GgufArchitectureType.falconH1:
            case GgufArchitectureType.plamo2:
            case GgufArchitectureType.granitehybrid:
            case GgufArchitectureType.lfm2:
            case GgufArchitectureType.lfm2moe:
            case GgufArchitectureType.nemotronH:
            case GgufArchitectureType.nemotronHMoe:
            case GgufArchitectureType.qwen3next:
            case GgufArchitectureType.kimiLinear:
            case GgufArchitectureType.qwen35:
            case GgufArchitectureType.qwen35moe:
                return true;
        }

        return false;
    }

    /**
     * Get the dominant tensor type used in the model file
     */
    public get dominantTensorType(): GgmlType | undefined {
        if (this._dominantTensorType == null)
            this._dominantTensorType = getDominantTensorType(this._ggufFileInfo.fullTensorInfo ?? []);

        return this._dominantTensorType;
    }

    public get supportsRanking() {
        if (this._supportsRanking != null)
            return this._supportsRanking;

        const layers = this._ggufFileInfo.fullTensorInfo ?? [];
        for (let i = layers.length - 1; i >= 0; i--) {
            const tensor = layers[i];
            if (tensor == null)
                continue;

            if (tensor.name === "cls.weight" || tensor.name === "cls.output.weight") {
                this._supportsRanking = this.tokens.sepToken != null || this.tokens.eosToken != null ||
                    isRankingTemplateValid(parseRankingTemplate(this._ggufFileInfo.metadata?.tokenizer?.["chat_template.rerank"]));
                this._supportsRanking &&= !(this.hasEncoder && this.hasDecoder); // encoder-decoder models are not supported

                return this._supportsRanking;
            }
        }

        this._supportsRanking = false;
        return this._supportsRanking;
    }

    /**
     * The size of the SWA (Sliding Window Attention).
     *
     * When `undefined`, the model does not use sliding window attention.
     */
    public get swaSize() {
        const slidingWindow = this._ggufFileInfo?.architectureMetadata?.attention?.sliding_window;
        if (slidingWindow == null || slidingWindow <= 0)
            return undefined;

        const trainContextSize = this.trainContextSize;
        if (trainContextSize != null && slidingWindow >= trainContextSize)
            return undefined;

        return slidingWindow;
    }

    /** @internal */
    public _getAddonMetadata(): Promisable<AddonGgufMetadata | undefined> {
        if (this._addonMetadata != null || this._ggufFileInfo.sourceData.length === 0)
            return this._addonMetadata;

        return withLock([this._locks, "addonMetadata"], async () => {
            if (this._addonMetadata != null)
                return this._addonMetadata;

            const initInput: Array<Buffer | string> = [];
            for (const data of this._ggufFileInfo.sourceData) {
                if (data.type === "buffer")
                    initInput.push(data.buffer);
                else if (data.type === "path")
                    initInput.push(data.path);
                else
                    void (data satisfies never);
            }

            const addonMetadata = new this._llama._bindings.AddonGgufMetadata();
            await addonMetadata.init(initInput);
            this._addonMetadata = addonMetadata;
            return addonMetadata;
        });
    }

    /**
     * @deprecated Use `estimateModelResourceRequirementsV2` instead
     */
    public estimateModelResourceRequirements({
        gpuLayers, useMmap = this._getUseMmap(), gpuSupportsMmap = this._llama.gpuSupportsMmap
    }: {
        gpuLayers: number, useMmap?: boolean, gpuSupportsMmap?: boolean
    }): GgufInsightsResourceRequirements {
        const {cpu, gpu} = this._getTensorResourceSplit(gpuLayers);

        return {
            cpuRam: calculateTensorsSize(cpu, this._llama, false),
            gpuVram: calculateTensorsSize(gpu, this._llama, useMmap && gpuSupportsMmap)
        };
    }

    public async estimateModelResourceRequirementsV2(options: {
        gpuLayers: number, useMmap?: boolean, gpuSupportsMmap?: boolean,

        /** @internal */
        _simulatorSession?: GgufInsightsSimulatorSession
    }): Promise<GgufInsightsResourceRequirements> {
        const {
            gpuLayers, useMmap = this._getUseMmap(), gpuSupportsMmap = this._llama.gpuSupportsMmap,

            _simulatorSession
        } = options;

        try {
            const simulationResult = await this._simulateModelResourceUsage({
                gpuLayers,
                useMmap,
                simulatorSession: _simulatorSession
            });

            if (simulationResult != null) {
                if (!useMmap || !gpuSupportsMmap)
                    return simulationResult;

                // adjust for the missing mmap simulation implementation
                const standardEstimation = this.estimateModelResourceRequirements({
                    gpuLayers,
                    useMmap,
                    gpuSupportsMmap
                });

                return {
                    gpuVram: Math.max(simulationResult.gpuVram, standardEstimation.gpuVram),
                    cpuRam: Math.min(simulationResult.cpuRam, standardEstimation.cpuRam)
                };
            }
        } catch (error: any) {
            this._llama._log(LlamaLogLevel.warn, error?.message ?? String(error));
        }

        return this.estimateModelResourceRequirements({
            gpuLayers,
            useMmap,
            gpuSupportsMmap
        });
    }

    /** @internal */
    public async _simulateModelResourceUsage({
        gpuLayers,
        useMmap = this._getUseMmap(),
        simulatorSession = this._simulationSession
    }: {
        gpuLayers: number,
        useMmap?: boolean,
        simulatorSession?: GgufInsightsSimulatorSession
    }): Promise<GgufInsightsResourceRequirements | null> {
        const cacheKey = [gpuLayers, Number(useMmap)].join(":");
        const cachedValue = this._exactModelResourceRequirementsCache.get(cacheKey);
        if (cachedValue != null)
            return {...cachedValue};

        const lock = await acquireLock([this._locks, "_simulateModelResourceUsage", cacheKey]);
        try {
            const cachedValue = this._exactModelResourceRequirementsCache.get(cacheKey);
            if (cachedValue != null)
                return {...cachedValue};

            const simulatorSource = await this._resolveSimulatorSource();
            if (simulatorSource == null)
                return null;
    
            let resourceRequirements: GgufInsightsResourceRequirements;
            try {
                resourceRequirements = await simulatorSession.estimateModelResources({
                    modelSource: simulatorSource,
                    gpuLayers,
                    useMmap
                });
            } catch (error: any) {
                throw new Error("Failed simulating model resource usage. Falling back to estimation heuristic. Error: " + (error?.message ?? String(error)));
            }
    
            this._exactModelResourceRequirementsCache.set(cacheKey, resourceRequirements);
            return {...resourceRequirements};
        } finally {
            lock.dispose();
        }
    }

    /**
     * Estimates the memory required to create a context of the given parameters based on the implementation details of `llama.cpp`.
     * The calculation doesn't include a precise estimation of the graph overhead memory, so it uses a rough estimate for that.
     * The estimation for the graph overhead memory will be improved in the future to be more precise, but it's good enough for now.
     * @deprecated Use `estimateContextResourceRequirementsV2` instead
     */
    public estimateContextResourceRequirements({
        contextSize, modelGpuLayers, batchSize, sequences, isEmbeddingContext = false, includeGraphOverhead = true, flashAttention = false,
        swaFullCache = false,
        kvCacheKeyType = GgmlType.F16, kvCacheValueType = GgmlType.F16
    }: {
        contextSize: number, modelGpuLayers: number, batchSize?: number, sequences?: number, isEmbeddingContext?: boolean,
        flashAttention?: boolean, includeGraphOverhead?: boolean, swaFullCache?: boolean,
        kvCacheKeyType?: GgmlType, kvCacheValueType?: GgmlType
    }): GgufInsightsResourceRequirements {
        if (sequences == null) sequences = getDefaultContextSequences();
        if (batchSize == null) batchSize = getDefaultContextBatchSize({contextSize, sequences});

        const llmData = this._ggufFileInfo.architectureMetadata;
        const tensorInfo = this._ggufFileInfo.fullTensorInfo ?? [];
        const slidingWindow = this.swaSize ?? 0;
        const kvUnified = false;
        const totalFileLayers = this._getTotalFileLayers();
        const hasSwaAttention = slidingWindow > 0;
        const usingReducedSWA = hasSwaAttention && !swaFullCache && slidingWindow < contextSize &&
            (this.trainContextSize == null || slidingWindow < this.trainContextSize);
        let graphRelevantTensorCount = 0;
        let graphRelevantTensorElements = 0;
        let totalTensorElements = 0;

        for (const singleTensorInfo of tensorInfo) {
            let tensorElements = 0;
            for (const dim of singleTensorInfo.dimensions)
                tensorElements += Number(dim);

            totalTensorElements += tensorElements;

            if (!isGraphRelevantTensor(singleTensorInfo.name))
                continue;

            graphRelevantTensorCount++;
            graphRelevantTensorElements += tensorElements;
        }

        const effectiveGraphTensorCount = graphRelevantTensorCount > 0
            ? graphRelevantTensorCount
            : tensorInfo.length;
        const effectiveGraphTensorElements = graphRelevantTensorCount > 0
            ? graphRelevantTensorElements
            : totalTensorElements;

        const paddedContextSize = padSafeContextSize(contextSize, "up");
        const actualContextSize = kvUnified
            ? padSafeContextSize(sequences * contextSize, "up")
            : sequences * paddedContextSize;
        const fullAttentionKvSize = actualContextSize;
        const swaBatchSize = hasSwaAttention && !swaFullCache
            ? batchSize + 1
            : batchSize;
        const swaKvSize = !hasSwaAttention
            ? actualContextSize
            : !usingReducedSWA
                ? actualContextSize
                : Math.min(actualContextSize, ggmlPad((sequences * slidingWindow) + swaBatchSize, 256));
        const totalLayersIncludingOutput = totalFileLayers + 1;
        const finalModelGpuLayers = Math.max(
            0,
            Math.min(modelGpuLayers ?? totalLayersIncludingOutput, totalLayersIncludingOutput)
        );
        const finalGpuLayers = Math.max(0, Math.min(modelGpuLayers ?? totalFileLayers, totalFileLayers));
        const finalCpuLayers = totalFileLayers - finalGpuLayers;
        const usingGpu = finalModelGpuLayers !== 0;

        const {
            gpuKVCacheSize,
            cpuKVCacheSize,
            gpuRecurrentStateSize,
            cpuRecurrentStateSize,
            maxAttentionLayerKvSize,
            maxAttentionLayerHeadCountKv
        } = this._estimateContextCacheMemorySplitInBytes({
            fullAttentionKvSize,
            swaKvSize,
            sequences,
            totalFileLayers,
            finalModelGpuLayers,
            usingGpu,
            flashAttention,
            kvCacheKeyType,
            kvCacheValueType
        });

        const vocabularySize = llmData.vocab_size ?? this._ggufFileInfo.metadata.tokenizer?.ggml?.tokens?.length ?? 0;
        const embeddingSize = llmData.embedding_length ?? 0;

        const floatBytes = 4; // sizeof(float)
        const int32TBytes = 4; // sizeof(int32_t)

        const estimateOutput = (nOutputs: number) => {
            // source: `llama_context::output_reserve` in `llama-context.cpp`
            const nOutputsMax = Math.max(batchSize, nOutputs);

            const isT5 = this._ggufFileInfo.metadata.general?.architecture === GgufArchitectureType.t5;
            const hasLogits = isT5 || !isEmbeddingContext;
            const hasEmbd = isT5 || isEmbeddingContext;

            const logitsSize = hasLogits
                ? (vocabularySize * nOutputsMax)
                : 0;
            const embdSize = hasEmbd
                ? (embeddingSize * nOutputsMax)
                : 0;
            const outputBufferSize = (logitsSize + embdSize) * floatBytes;

            const outputIdsArr = int32TBytes * batchSize;

            return outputBufferSize + outputIdsArr;
        };

        const estimateGraphOverheadMemory = (): number => {
            const s1MB = Math.pow(1024, 2);
            const expertCount = llmData?.expert_count ?? 0;
            const headCount = llmData?.attention?.head_count ?? 0;
            const embeddingLength = llmData?.embedding_length ?? 0;
            const activeGraphTokens = roundUpToMultiple(
                Math.max(1, Math.min(paddedContextSize, batchSize)),
                Math.max(1, sequences)
            );
            const graphContextSize = resolveGraphContextSizeForOverheadEstimation({
                fullAttentionKvSize,
                trainContextSize: this.trainContextSize,
                flashAttention,
                headCount,
                batchSize,
                paddedContextSize,
                sequences
            });

            let defaultCalculationAdjustment = 0;
            const totalElements = effectiveGraphTensorCount === 0
                ? this.totalLayers * (
                    (
                        (llmData.embedding_length ?? 0) +
                        (llmData.feed_forward_length ?? 0)
                    ) / 2
                )
                : effectiveGraphTensorElements;
            const tensorBasedGraphOverhead = (tensorElementMultiplier: number) => (
                (totalElements * tensorElementMultiplier * (graphContextSize / 4096)) + defaultCalculationAdjustment
            );
            const batchLocalTensorBasedGraphOverhead = (tensorElementMultiplier: number) => (
                (totalElements * tensorElementMultiplier * (activeGraphTokens / 4096)) + defaultCalculationAdjustment
            );

            if (batchSize == null)
                return 0;

            const genericNonFlashAttentionWorkspaceEstimate = !flashAttention
                ? estimateNonFlashAttentionWorkspace({
                    trainContextSize: this.trainContextSize,
                    fullAttentionKvSize,
                    swaKvSize,
                    hasSwaAttention,
                    maxAttentionLayerKvSize,
                    maxAttentionLayerHeadCountKv,
                    activeGraphTokens,
                    headCount
                })
                : 0;

            if (this._ggufFileInfo.metadata.general?.architecture === GgufArchitectureType.llama) {
                if (expertCount > 0) {
                    const expertsUsedCount = this._ggufFileInfo.architectureMetadata.expert_used_count ?? 2;

                    return Math.max(
                        int32TBytes * batchSize * (((expertsUsedCount + 1) * embeddingLength) + (graphContextSize * headCount)),
                        genericNonFlashAttentionWorkspaceEstimate
                    );
                }

                return Math.max(
                    int32TBytes * batchSize * (embeddingLength + (graphContextSize * headCount)),
                    genericNonFlashAttentionWorkspaceEstimate
                );
            } else if (this._ggufFileInfo.metadata.general?.architecture === GgufArchitectureType.qwen2) {
                if (modelGpuLayers === this.totalLayers) {
                    defaultCalculationAdjustment -= (s1MB * 340) * (
                        this.trainContextSize == null
                            ? 1
                            : graphContextSize / this.trainContextSize
                    );
                } else {
                    defaultCalculationAdjustment -= (s1MB * 250) + (
                        (s1MB * 50) * (
                            this.trainContextSize == null
                                ? 1
                                : graphContextSize / this.trainContextSize
                        )
                    );
                }
            } else if (this._ggufFileInfo.metadata.general?.architecture === GgufArchitectureType.gemma) {
                // only works properly when all layers are on the GPU, which is why it's commented out:
                // return int32TBytes * batchSize * ((llmData.embedding_length ?? 0));

                if (modelGpuLayers === this.totalLayers) {
                    defaultCalculationAdjustment += (s1MB * 40) - (
                        (s1MB * 270) * (
                            this.trainContextSize == null
                                ? 1
                                : graphContextSize / this.trainContextSize
                        )
                    );
                } else {
                    defaultCalculationAdjustment += -(s1MB * 550) + (
                        (s1MB * 150) * (
                            this.trainContextSize == null
                                ? 1
                                : Math.max(0, (1 - (graphContextSize / this.trainContextSize)))
                        )
                    );
                }
            } else if (this._ggufFileInfo.metadata.general?.architecture === GgufArchitectureType.gemma3) {
                const trainContextSize = Math.max(1, this.trainContextSize ?? graphContextSize);
                const contextRatio = Math.min(1, Math.max(0, graphContextSize / trainContextSize));

                return Math.max(
                    int32TBytes * batchSize * graphContextSize * headCount * (0.08 + Math.pow(contextRatio, 2)),
                    genericNonFlashAttentionWorkspaceEstimate
                );
            } else if (this._ggufFileInfo.metadata.general?.architecture === GgufArchitectureType.stablelm) {
                const headCount = this._ggufFileInfo.architectureMetadata.attention?.head_count ?? 0;

                return Math.max(
                    (int32TBytes * batchSize * graphContextSize * headCount) - (50 * s1MB),
                    genericNonFlashAttentionWorkspaceEstimate
                );

                // if (modelGpuLayers === this.totalLayers) {
                //     defaultCalculationAdjustment += -(s1MB * 20) + (
                //         (s1MB * 250) * (
                //             this.trainContextSize == null
                //                 ? 1
                //                 : kvSize / this.trainContextSize
                //         )
                //     );
                // } else {
                //     defaultCalculationAdjustment += -(s1MB * 40) + (
                //         (s1MB * 300) * (
                //             this.trainContextSize == null
                //                 ? 1
                //                 : kvSize / this.trainContextSize
                //         )
                //     );
                // }
            } else if (this._ggufFileInfo.metadata.general?.architecture === GgufArchitectureType.qwen3) {
                return Math.max(
                    int32TBytes * batchSize * (embeddingLength + (graphContextSize * headCount)),
                    genericNonFlashAttentionWorkspaceEstimate
                );
            } else if (this._ggufFileInfo.metadata.general?.architecture === GgufArchitectureType.gemma4) {
                const trainContextSize = Math.max(1, this.trainContextSize ?? graphContextSize);
                const contextRatio = Math.min(1, Math.max(0, graphContextSize / trainContextSize));
                const gemma4DenseShortContextScale = 0.4;
                const gemma4DenseContextScaleExponent = 3;
                const gemma4DenseEstimate = int32TBytes * batchSize * graphContextSize * headCount *
                    (gemma4DenseShortContextScale + Math.pow(contextRatio, gemma4DenseContextScaleExponent));

                if (expertCount > 0) {
                    const tensorBasedEstimate = tensorBasedGraphOverhead(77.655);
                    const moeBlendWeight = Math.sqrt(contextRatio);

                    return Math.max(
                        gemma4DenseEstimate,
                        (gemma4DenseEstimate + ((tensorBasedEstimate - gemma4DenseEstimate) * moeBlendWeight)) * 1.01,
                        genericNonFlashAttentionWorkspaceEstimate
                    );
                }

                return Math.max(gemma4DenseEstimate, genericNonFlashAttentionWorkspaceEstimate);
            } else if (expertCount > 0) {
                const expertsUsedCount = this._ggufFileInfo.architectureMetadata.expert_used_count ?? 2;

                return Math.max(
                    int32TBytes * batchSize * (((expertsUsedCount + 1) * embeddingLength) + (graphContextSize * headCount)),
                    genericNonFlashAttentionWorkspaceEstimate
                );
            }

            if (this._ggufFileInfo.metadata.general?.architecture === GgufArchitectureType.phi3) {
                // magic numbers for estimation. will be improved in the future
                return Math.max(tensorBasedGraphOverhead(123), genericNonFlashAttentionWorkspaceEstimate);
            } else if (this._ggufFileInfo.metadata.general?.architecture === GgufArchitectureType.cohere2) {
                // magic numbers for estimation. will be improved in the future
                return Math.max(tensorBasedGraphOverhead(148), genericNonFlashAttentionWorkspaceEstimate);
            }

            // magic numbers for estimation. will be improved in the future
            return Math.max(
                !flashAttention
                    ? batchLocalTensorBasedGraphOverhead(77.655)
                    : tensorBasedGraphOverhead(77.655),
                genericNonFlashAttentionWorkspaceEstimate
            );
        };

        // source: `llama_context::graph_max_nodes` in `llama-context.cpp`
        const getMaxNodesMultiplier = (arch: GgufArchitectureType | undefined, nTokens: number): {min: number, multiplier: number} => {
            if (arch === GgufArchitectureType.qwen3next)
                return {
                    min: nTokens * 40,
                    multiplier: 32
                };

            return {
                min: 1024,
                multiplier: 8
            };
        };
        const maxNodesMultiplier = getMaxNodesMultiplier(
            this._ggufFileInfo.metadata?.general?.architecture,
            Math.min(actualContextSize, batchSize)
        );
        const maxNodes = Math.max(maxNodesMultiplier.min, maxNodesMultiplier.multiplier * effectiveGraphTensorCount);
        const cpuNodes = totalFileLayers === 0
            ? 0
            : maxNodesMultiplier.multiplier * (effectiveGraphTensorCount * (finalCpuLayers / totalFileLayers));
        const gpuNodes = maxNodes - cpuNodes;

        const gpuComputeBufferSize = (this._llama._consts.ggmlTensorOverhead * gpuNodes) +
            this._llama._bindings.getGgmlGraphOverheadCustom(gpuNodes, false);
        const cpuComputeBufferSize = (this._llama._consts.ggmlTensorOverhead * cpuNodes) +
            this._llama._bindings.getGgmlGraphOverheadCustom(cpuNodes, false);

        const graphOverheadMemory = !includeGraphOverhead
            ? 0
            : estimateGraphOverheadMemory();
        const graphOverheadGpuSize = (usingGpu && totalFileLayers > 0)
            ? Math.round(graphOverheadMemory * (finalGpuLayers / totalFileLayers))
            : 0;
        const graphOverheadCpuSize = graphOverheadMemory - graphOverheadGpuSize;

        const outputBufferSize = estimateOutput(sequences);

        const gpuVram = gpuKVCacheSize + gpuRecurrentStateSize + gpuComputeBufferSize + graphOverheadGpuSize + outputBufferSize;
        const cpuRam = cpuKVCacheSize + cpuRecurrentStateSize + cpuComputeBufferSize + graphOverheadCpuSize + outputBufferSize;

        return {
            cpuRam,
            gpuVram: usingGpu
                ? gpuVram
                : 0
        };
    }

    public async estimateContextResourceRequirementsV2(options: {
        contextSize: number, modelGpuLayers: number, batchSize?: number, sequences?: number, isEmbeddingContext?: boolean,
        flashAttention?: LlamaContextOptions["flashAttention"], swaFullCache?: boolean,
        kvCacheKeyType?: GgmlType, kvCacheValueType?: GgmlType,
        useMmap?: boolean,

        /** @internal */
        _simulatorSession?: GgufInsightsSimulatorSession
    }): Promise<GgufInsightsResourceRequirements> {
        const {
            contextSize, modelGpuLayers, batchSize, sequences, isEmbeddingContext = false, flashAttention = "auto",
            swaFullCache = false,
            kvCacheKeyType = GgmlType.F16, kvCacheValueType = GgmlType.F16,
            useMmap,

            _simulatorSession
        } = options;

        try {
            const simulationResult = await this._simulateContextResourceUsage({
                contextSize,
                modelGpuLayers,
                batchSize,
                sequences,
                isEmbeddingContext,
                flashAttention,
                swaFullCache,
                useMmap,
                simulatorSession: _simulatorSession,
                kvCacheKeyType,
                kvCacheValueType
            });
            if (simulationResult != null)
                return simulationResult;
        } catch (error: any) {
            this._llama._log(LlamaLogLevel.warn, error?.message ?? String(error));
        }

        return this.estimateContextResourceRequirements({
            contextSize,
            modelGpuLayers,
            batchSize,
            sequences,
            isEmbeddingContext,
            flashAttention: flashAttention === true,
            swaFullCache,
            kvCacheKeyType,
            kvCacheValueType
        });
    }

    /** @internal */
    public _getUseMmap(useMmapOption?: boolean) {
        return useMmapOption ?? this._defaultUseMmap ?? this._llama.supportsMmap;
    }

    /** @internal */
    public async _simulateContextResourceUsage({
        contextSize, modelGpuLayers, batchSize, sequences, isEmbeddingContext = false, flashAttention = "auto",
        swaFullCache = false, useMmap = this._getUseMmap(),
        kvCacheKeyType = GgmlType.F16, kvCacheValueType = GgmlType.F16,
        simulatorSession = this._simulationSession
    }: {
        contextSize: number, modelGpuLayers: number, batchSize?: number, sequences?: number, isEmbeddingContext?: boolean,
        flashAttention?: LlamaContextOptions["flashAttention"], swaFullCache?: boolean, useMmap?: boolean,
        kvCacheKeyType?: GgmlType, kvCacheValueType?: GgmlType,
        simulatorSession?: GgufInsightsSimulatorSession
    }): Promise<GgufInsightsResourceRequirements | null> {
        if (sequences == null) sequences = getDefaultContextSequences();
        if (batchSize == null) batchSize = getDefaultContextBatchSize({contextSize, sequences});

        const kvUnified = false;

        const cacheKey = [
            contextSize,
            modelGpuLayers,
            batchSize,
            sequences,
            Number(isEmbeddingContext),
            flashAttention === "auto"
                ? "auto"
                : String(flashAttention),
            Number(swaFullCache),
            Number(useMmap),
            kvCacheKeyType,
            kvCacheValueType
        ].join(":");
        const cachedValue = this._exactContextResourceRequirementsCache.get(cacheKey);
        if (cachedValue != null)
            return {...cachedValue};

        const lock = await acquireLock([this._locks, "_simulateContextResourceUsage", cacheKey]);
        try {
            const cachedValue = this._exactContextResourceRequirementsCache.get(cacheKey);
            if (cachedValue != null)
                return {...cachedValue};

            const simulatorSource = await this._resolveSimulatorSource();
            if (simulatorSource == null)
                return null;
    
            let contextResources: GgufInsightsResourceRequirements;
            try {
                const paddedContextSize = padSafeContextSize(contextSize, "up");
                const actualContextSize = kvUnified
                    ? padSafeContextSize(sequences * contextSize, "up")
                    : sequences * paddedContextSize;
                const actualBatchSize = Math.max(batchSize, sequences) + (
                    (!swaFullCache && this.swaSize != null && this.swaSize > 0)
                        ? 1 // +1 to handle edge cases with SWA KV cache
                        : 0
                );

                contextResources = await simulatorSession.estimateContextResources({
                    modelSource: simulatorSource,
                    gpuLayers: modelGpuLayers,
                    contextSize: actualContextSize,
                    batchSize: actualBatchSize,
                    sequences,
                    isEmbeddingContext,
                    flashAttention,
                    swaFullCache,
                    useMmap,
                    kvCacheKeyType,
                    kvCacheValueType
                });
            } catch (error: any) {
                throw new Error("Failed simulating context resource usage. Falling back to estimation heuristic. Error: " + (error?.message ?? String(error)));
            }

            const resourceRequirements = {
                cpuRam: contextResources.cpuRam,
                gpuVram: contextResources.gpuVram
            } satisfies GgufInsightsResourceRequirements;
    
            this._exactContextResourceRequirementsCache.set(cacheKey, resourceRequirements);
            return {...resourceRequirements};
        } finally {
            lock.dispose();
        }
    }

    /**
     * Get the split tensor resources for CPU and GPU based on the number of GPU layers
     * @internal
     */
    public _getTensorResourceSplit(gpuLayers: number): {
        cpu: GgufTensorInfo[],
        gpu: GgufTensorInfo[]
    } {
        const tensorInfo = this._ggufFileInfo.fullTensorInfo ?? [];
        const architecture = this._ggufFileInfo.metadata?.general?.architecture;

        if (gpuLayers === 0) {
            return {
                cpu: tensorInfo,
                gpu: []
            };
        }

        const fileLayers = this._getFileLayers();
        const startGpuLayer = Math.max(0, fileLayers - gpuLayers + 1);

        const gpuTensors: GgufTensorInfo[] = [];
        const cpuTensors: GgufTensorInfo[] = [];

        let tokenEmbedLayer: GgufTensorInfo | undefined;
        let mainOutputLayer: GgufTensorInfo | undefined;

        for (const singleTensorInfo of tensorInfo) {
            if (isMainOutputLayer(singleTensorInfo.name))
                mainOutputLayer = singleTensorInfo;
            else if (isTokenEmbedLayer(singleTensorInfo.name))
                tokenEmbedLayer = singleTensorInfo;

            // in the implementation of `llm_load_tensors`, layers with `LLM_TENSOR_LAYER_INPUT` are always
            // loaded with `model.dev_input`, which is always set to the CPU
            if (isInputLayer(singleTensorInfo.name)) {
                cpuTensors.push(singleTensorInfo);
                continue;

            // in the implementation of `llm_load_tensors`, layers with `LLM_TENSOR_LAYER_OUTPUT` are always
            // loaded with `model.dev_output`, which is set to the GPU only if all the layers are on the GPU
            } else if (isOutputLayer(singleTensorInfo.name)) {
                if (gpuLayers > 0) {
                    gpuTensors.push(singleTensorInfo);
                    continue;
                } else {
                    cpuTensors.push(singleTensorInfo);
                    continue;
                }
            }

            const {layerNumber} = parseTensorName(singleTensorInfo.name);

            if (gpuLayers !== this.totalLayers) {
                if (architecture === GgufArchitectureType.qwen2 || architecture === GgufArchitectureType.gemma) {
                    if (layerNumber != null && layerNumber >= startGpuLayer)
                        gpuTensors.push(singleTensorInfo);
                    else
                        cpuTensors.push(singleTensorInfo);

                    continue;
                }
            }

            if (layerNumber == null || layerNumber >= startGpuLayer)
                gpuTensors.push(singleTensorInfo);
            else
                cpuTensors.push(singleTensorInfo);
        }

        if (mainOutputLayer == null && tokenEmbedLayer != null && gpuLayers === this.totalLayers && !gpuTensors.includes(tokenEmbedLayer))
            gpuTensors.push(tokenEmbedLayer);

        return {
            cpu: cpuTensors,
            gpu: gpuTensors
        };
    }

    /** @internal */
    public _determineNumberOfLayersFromTensorInfo(): number {
        const layerNumbers = new Set<number>();

        for (const singleTensorInfo of (this._ggufFileInfo.fullTensorInfo ?? [])) {
            const {layerNumber} = parseTensorName(singleTensorInfo.name);

            if (layerNumber != null)
                layerNumbers.add(layerNumber);
        }

        return layerNumbers.size;
    }

    /** @internal */
    public _getFileLayers() {
        return this._ggufFileInfo.architectureMetadata.block_count ?? this._determineNumberOfLayersFromTensorInfo();
    }

    private _estimateContextCacheMemorySplitInBytes({
        fullAttentionKvSize,
        swaKvSize,
        sequences,
        totalFileLayers,
        finalModelGpuLayers,
        usingGpu,
        flashAttention,
        kvCacheKeyType = GgmlType.F16,
        kvCacheValueType = GgmlType.F16
    }: {
        fullAttentionKvSize: number,
        swaKvSize: number,
        sequences: number,
        totalFileLayers: number,
        finalModelGpuLayers: number,
        usingGpu: boolean,
        flashAttention: boolean,
        kvCacheKeyType?: GgmlType,
        kvCacheValueType?: GgmlType
    }) {
        // source: `llama_kv_cache_init` in `llama.cpp`
        const architecture = this._ggufFileInfo.metadata.general?.architecture;
        const nHead = this._ggufFileInfo.architectureMetadata.attention?.head_count ?? 0;
        const nEmbd = this._ggufFileInfo.architectureMetadata.embedding_length ?? 0;
        const nEmbdHeadK = this._ggufFileInfo.architectureMetadata.attention?.key_length ?? ((nHead == 0) ? 0 : (nEmbd / nHead));
        const nHeadKv: number | number[] = this._ggufFileInfo.architectureMetadata.attention?.head_count_kv ?? nHead;
        const nEmbdHeadV = this._ggufFileInfo.architectureMetadata.attention?.value_length ?? ((nHead == 0) ? 0 : nEmbd / nHead);
        const nEmbdHeadKSwa = this._ggufFileInfo.architectureMetadata.attention?.key_length_swa;
        const nEmbdHeadVSwa = this._ggufFileInfo.architectureMetadata.attention?.value_length_swa;
        const sharedKvLayers = this._ggufFileInfo.architectureMetadata.attention?.shared_kv_layers;
        const slidingWindowPattern = this._ggufFileInfo.architectureMetadata.attention?.sliding_window_pattern;
        const keyTypeSize = this._llama._bindings.getTypeSizeForGgmlType(kvCacheKeyType) ?? this._llama._consts.ggmlTypeF16Size;
        const valueTypeSize = this._llama._bindings.getTypeSizeForGgmlType(kvCacheValueType) ?? this._llama._consts.ggmlTypeF16Size;
        const nHeadKvValues = nHeadKv as unknown;
        let maxLayerValueEmbedding = 0;

        if (!flashAttention && nHeadKvValues instanceof Array) {
            for (let i = 0; i < totalFileLayers; i++) {
                const layerHeadCountKv = resolveLayerHeadCountKv(nHeadKvValues, i, nHead);
                const isSwaLayer = isSwaLayerAtIndex(architecture, slidingWindowPattern, i);
                const layerValueEmbedding = resolveLayerHeadDimension(nEmbdHeadV, nEmbdHeadVSwa, isSwaLayer) * layerHeadCountKv;

                maxLayerValueEmbedding = Math.max(maxLayerValueEmbedding, layerValueEmbedding);
            }
        }

        // source: `llama_model::load_tensors` in `llama-model.cpp`
        // repeating layers are assigned to GPU from `i_gpu_start = n_layer + 1 - n_gpu_layers`
        const gpuRepeatingLayerStart = Math.max(0, (totalFileLayers + 1) - finalModelGpuLayers);
        const recurrentLayersByPattern = this.isRecurrent
            ? "all"
            : getRecurrentLayersPattern(architecture, this._ggufFileInfo.architectureMetadata);
        let gpuKvElementsK = 0;
        let gpuKvElementsV = 0;
        let cpuKvElementsK = 0;
        let cpuKvElementsV = 0;
        let gpuRecurrentLayers = 0;
        let cpuRecurrentLayers = 0;
        let maxAttentionLayerKvSize = 0;
        let maxAttentionLayerHeadCountKv = 0;

        for (let i = 0; i < totalFileLayers; i++) {
            const isGpuLayer = i >= gpuRepeatingLayerStart;
            const isRecurrentLayer = isLayerRecurrent(recurrentLayersByPattern, i);

            if (isRecurrentLayer) {
                if (isGpuLayer)
                    gpuRecurrentLayers++;
                else
                    cpuRecurrentLayers++;
            } else {
                if (!doesLayerOwnKvCache(totalFileLayers, i, sharedKvLayers))
                    continue;

                const nHeadKvLayer = resolveLayerHeadCountKv(nHeadKv, i, nHead);
                const isSwaLayer = isSwaLayerAtIndex(architecture, slidingWindowPattern, i);
                const layerKvSize = isSwaLayer
                    ? swaKvSize
                    : fullAttentionKvSize;
                maxAttentionLayerKvSize = Math.max(maxAttentionLayerKvSize, layerKvSize);
                maxAttentionLayerHeadCountKv = Math.max(maxAttentionLayerHeadCountKv, nHeadKvLayer);
                const layerElementsK = resolveLayerHeadDimension(nEmbdHeadK, nEmbdHeadKSwa, isSwaLayer) * nHeadKvLayer * layerKvSize;
                const layerElementsV = layerKvSize * (
                    maxLayerValueEmbedding > 0
                        ? maxLayerValueEmbedding
                        : (resolveLayerHeadDimension(nEmbdHeadV, nEmbdHeadVSwa, isSwaLayer) * nHeadKvLayer)
                );

                if (isGpuLayer) {
                    gpuKvElementsK += layerElementsK;
                    gpuKvElementsV += layerElementsV;
                } else {
                    cpuKvElementsK += layerElementsK;
                    cpuKvElementsV += layerElementsV;
                }
            }
        }

        const gpuKVCacheSize = usingGpu
            ? ((gpuKvElementsK * keyTypeSize) + (gpuKvElementsV * valueTypeSize))
            : 0;
        const cpuKVCacheSize = (cpuKvElementsK * keyTypeSize) + (cpuKvElementsV * valueTypeSize);

        const recurrentCellSize = Math.max(1, sequences);
        const gpuRecurrentStateSize = usingGpu
            ? this._estimateRecurrentStateMemorySizeInBytes(recurrentCellSize, gpuRecurrentLayers)
            : 0;
        const cpuRecurrentStateSize = this._estimateRecurrentStateMemorySizeInBytes(recurrentCellSize, cpuRecurrentLayers);

        return {
            gpuKVCacheSize,
            cpuKVCacheSize,
            gpuRecurrentStateSize,
            cpuRecurrentStateSize,
            maxAttentionLayerKvSize,
            maxAttentionLayerHeadCountKv
        };
    }

    private _estimateRecurrentStateMemorySizeInBytes(recurrentCellSize: number, layers: number) {
        if (layers <= 0 || recurrentCellSize <= 0)
            return 0;

        // source: `llama_memory_recurrent` + `llama_hparams::n_embd_r` / `llama_hparams::n_embd_s` in `llama.cpp`
        const nHead = this._ggufFileInfo.architectureMetadata.attention?.head_count ?? 0;
        const nEmbd = this._ggufFileInfo.architectureMetadata.embedding_length ?? 0;
        const wkvHeadSize = this._ggufFileInfo.architectureMetadata.wkv?.head_size ?? 0;
        const tokenShiftCount = this._ggufFileInfo.architectureMetadata.token_shift_count ?? 0;
        const ssmDConv = this._ggufFileInfo.architectureMetadata.ssm?.conv_kernel ?? 0;
        const ssmDInner = this._ggufFileInfo.architectureMetadata.ssm?.inner_size ?? 0;
        const ssmDState = this._ggufFileInfo.architectureMetadata.ssm?.state_size ?? 0;
        const ssmGroupCount = this._ggufFileInfo.architectureMetadata.ssm?.group_count ?? 0;
        const shortConvLCache = this._ggufFileInfo.architectureMetadata.shortconv?.l_cache ?? 0;
        const kdaHeadDim = this._ggufFileInfo.architectureMetadata.kda?.head_dim ?? 0;
        const shortConvHistoryShift = 1;
        const kdaQkvStateCount = 3;
        const kdaDefaultConvKernel = 3;
        const ssmBcStatePairCount = 2;

        const nEmbdR = wkvHeadSize !== 0
            ? tokenShiftCount * nEmbd
            : shortConvLCache !== 0
                ? nEmbd * Math.max(0, shortConvLCache - shortConvHistoryShift)
                : kdaHeadDim !== 0
                    ? (
                        kdaQkvStateCount * (
                            ssmDConv > 0
                                ? ssmDConv - shortConvHistoryShift
                                : kdaDefaultConvKernel
                        ) * (nHead * kdaHeadDim)
                    )
                    : (
                        (
                            ssmDConv > 0
                                ? (ssmDConv - shortConvHistoryShift)
                                : 0
                        ) * (ssmDInner + (ssmBcStatePairCount * ssmGroupCount * ssmDState))
                    );
        const nEmbdS = wkvHeadSize !== 0
            ? nEmbd * wkvHeadSize
            : kdaHeadDim !== 0
                ? kdaHeadDim * kdaHeadDim * nHead
                : ssmDState * ssmDInner;

        if (nEmbdR === 0 && nEmbdS === 0)
            return 0;

        const recurrentTypeSize = this._llama._consts.ggmlTypeF32Size;
        const bytesPerLayer = (nEmbdR + nEmbdS) * recurrentTypeSize;

        return layers * recurrentCellSize * bytesPerLayer;
    }

    /** @internal */
    private _getTotalFileLayers() {
        if (this._totalFileLayers != null)
            return this._totalFileLayers;

        this._totalFileLayers = this._getFileLayers();

        return this._totalFileLayers;
    }

    /** @internal */
    private async _resolveSimulatorSource(): Promise<string | AddonGgufMetadata | null> {
        const addonMetadata = await this._getAddonMetadata();
        if (addonMetadata != null)
            return addonMetadata;

        if (this._ggufFileInfo.source?.type === "path")
            return this._ggufFileInfo.source.path;

        return null;
    }

    /** @internal */
    public _createSimulatorSession(lruCacheSize: number = 10) {
        return new GgufInsightsSimulatorSession(this._llama, lruCacheSize);
    }

    /**
     * @param ggufFileInfo
     * @param llama - If you already have a `Llama` instance, pass it to reuse it for the `GgufInsights` instance.
     * If you don't pass a `Llama` instance, a basic `Llama` instance is created as a fallback - it's a slim instance that
     * doesn't instantiate a `llama.cpp` backend, so it won't utilize the GPU at all, and be shared with other `GgufInsights` instances
     * that need a fallback `Llama` instance.
     */
    public static async from(ggufFileInfo: GgufFileInfo, llama?: Llama) {
        let resolvedLlama = llama;
        if (resolvedLlama == null)
            resolvedLlama = await getLlamaWithoutBackend();

        return new GgufInsights(ggufFileInfo, resolvedLlama);
    }
}

export class GgufInsightsSimulatorSession {
    private readonly _llama: Llama;
    private readonly _modelPromises: LruCache<string, Promise<AddonModel>>;
    private _disposed = false;

    public constructor(llama: Llama, lruCacheSize: number = 10) {
        this._llama = llama;
        this._modelPromises = new LruCache(lruCacheSize);
    }

    public async estimateModelResources({
        modelSource,
        gpuLayers,
        useMmap = false
    }: {
        modelSource: string | AddonGgufMetadata,
        gpuLayers: number,
        useMmap?: boolean
    }): Promise<GgufInsightsResourceRequirements> {
        const model = await this._getModel({source: modelSource, gpuLayers, useMmap});
        const memoryBreakdown = model.getMemoryBreakdown();
        if (this._llama._shouldLog(LlamaLogLevel.debug))
            this._llama._log(LlamaLogLevel.debug, "Simulating model resource usage. " + [
                `gpuLayers=${gpuLayers}`,
                `useMmap=${useMmap}`,
                `memoryBreakdownCpuRam=${bytes(memoryBreakdown.cpuRam)}`,
                `memoryBreakdownGpuVram=${bytes(memoryBreakdown.gpuVram)}`
            ].join(" "));
        return memoryBreakdown;
    }

    public async estimateContextResources({
        modelSource,
        gpuLayers,
        contextSize,
        batchSize,
        sequences,
        isEmbeddingContext = false,
        flashAttention = "auto",
        swaFullCache = false,
        useMmap = false,
        kvCacheKeyType = GgmlType.F16,
        kvCacheValueType = GgmlType.F16
    }: {
        modelSource: string | AddonGgufMetadata,
        gpuLayers: number,
        contextSize: number,
        batchSize: number,
        sequences: number,
        isEmbeddingContext?: boolean,
        flashAttention?: LlamaContextOptions["flashAttention"],
        swaFullCache?: boolean,
        useMmap?: boolean,
        kvCacheKeyType?: GgmlType,
        kvCacheValueType?: GgmlType
    }): Promise<GgufInsightsResourceRequirements> {
        const model = await this._getModel({source: modelSource, gpuLayers, useMmap});
        const context = new this._llama._bindings.AddonContext(model, removeUndefinedFields({
            contextSize,
            batchSize,
            sequences,
            embeddings: isEmbeddingContext,
            flashAttention: flashAttention === "auto"
                ? "auto"
                : flashAttention,
            kvCacheKeyType,
            kvCacheValueType,
            swaFullCache
        } satisfies AddonContextParams));

        try {
            const contextLoaded = await context.init();
            if (!contextLoaded)
                throw new Error("Failed to create context");
            
            const memoryBreakdown = context.getMemoryBreakdown();
            if (this._llama._shouldLog(LlamaLogLevel.debug))
                this._llama._log(LlamaLogLevel.debug, "Simulating context resource usage. " + [
                    `gpuLayers=${gpuLayers}`,
                    `contextSize=${contextSize.toLocaleString("en-US", {notation: "compact"})}`,
                    `batchSize=${batchSize}`,
                    `sequences=${sequences}`,
                    `isEmbeddingContext=${isEmbeddingContext}`,
                    `flashAttention=${flashAttention}`,
                    `swaFullCache=${swaFullCache}`,
                    `kvCacheKeyType=${kvCacheKeyType}`,
                    `kvCacheValueType=${kvCacheValueType}`,
                    `useMmap=${useMmap}`,
                    `memoryBreakdownCpuRam=${bytes(memoryBreakdown.cpuRam)}`,
                    `memoryBreakdownGpuVram=${bytes(memoryBreakdown.gpuVram)}`
                ].join(" "));
            return memoryBreakdown;
        } finally {
            await context.dispose();
        }
    }

    public [Symbol.asyncDispose]() {
        return this.dispose();
    }

    public async dispose() {
        if (this._disposed)
            return;

        this._disposed = true;

        const modelPromises = [...this._modelPromises.values()].map((modelPromise) => modelPromise.catch(() => void 0));
        this._modelPromises.clear();
        const loadedModels = (await Promise.all(modelPromises)).filter((model) => model != null);

        await Promise.all(loadedModels.map((model) => model.dispose().catch(() => void 0)));
    }

    private async _getModel({
        source,
        gpuLayers,
        useMmap = this._llama.supportsMmap
    }: {
        source: string | AddonGgufMetadata,
        gpuLayers: number,
        useMmap?: boolean
    }) {
        if (this._disposed)
            throw new Error("simulator session is disposed");

        const cacheKey = String(gpuLayers) + ":" + String(useMmap);
        const existingModelPromise = this._modelPromises.get(cacheKey);
        if (existingModelPromise != null)
            return await existingModelPromise;

        if (this._llama._shouldLog(LlamaLogLevel.debug))
            this._llama._log(LlamaLogLevel.debug, `Loading model for simulator session. gpuLayers=${gpuLayers} useMmap=${useMmap}`);
        const modelPromise = this._loadModel({
            source,
            gpuLayers,
            useMmap
        });
        this._modelPromises.set(cacheKey, modelPromise);

        try {
            return await modelPromise;
        } catch (error) {
            this._modelPromises.delete(cacheKey);
            throw error;
        }
    }

    private async _loadModel({
        source, gpuLayers, useMmap = false
    }: {
        source: string | AddonGgufMetadata, gpuLayers: number, useMmap?: boolean
    }) {
        const model = new this._llama._bindings.AddonModel(
            typeof source === "string"
                ? source
                : "",
            removeNullFields({
                gpuLayers,
                noAlloc: true,
                useMmap,
                useMlock: false
            } satisfies AddonModelParams)
        );

        const loadingLock = await acquireLock([this._llama._memoryLock, LlamaLocks.loadToMemory]);
        try {
            const modelLoaded = typeof source === "string"
                ? await model.init()
                : await model.init(source);
            if (!modelLoaded)
                throw new Error("Failed to load model");
        } finally {
            loadingLock.dispose();
        }

        return model;
    }
}

function parseTensorName(tensorName?: string): {
    layerNumber: number | undefined
} {
    if (tensorName == null)
        return {layerNumber: undefined};

    const layerTensorPrefix = "blk.";
    if (!tensorName.startsWith(layerTensorPrefix))
        return {layerNumber: undefined};

    const dotIndex = tensorName.indexOf(".", layerTensorPrefix.length);
    const layerNumberString = tensorName.slice(
        layerTensorPrefix.length,
        dotIndex < 0
            ? tensorName.length
            : dotIndex
    );

    const layerNumber = parseInt(layerNumberString);
    if (Number.isFinite(layerNumber))
        return {layerNumber};

    return {layerNumber: undefined};
}

function calculateTensorsSize(
    tensorsInfo: GgufTensorInfo[],
    llama: Llama,
    useMmap: boolean,
    startFromTensorDataOffset: boolean = false
) {
    if (!useMmap) {
        let size = 0;
        for (const tensorInfo of tensorsInfo)
            size += calculateTensorSize(tensorInfo, llama);

        return size;
    }

    const fileStats = new Map<number, {
        tensorsSize: number,
        startOffset?: number | bigint,
        endOffset?: number | bigint
    }>();
    for (const tensorInfo of tensorsInfo) {
        let stats = fileStats.get(tensorInfo.filePart);
        if (stats == null) {
            stats = {
                tensorsSize: 0
            };
            fileStats.set(tensorInfo.filePart, stats);
        }

        const tensorSize = calculateTensorSize(tensorInfo, llama);
        stats.tensorsSize += tensorSize;
        const startOffset = tensorInfo.offset;
        const endOffset = typeof startOffset === "number"
            ? startOffset + tensorSize
            : startOffset + BigInt(tensorSize);

        if (startFromTensorDataOffset)
            stats.startOffset = Number(BigInt(tensorInfo.fileOffset) - BigInt(tensorInfo.offset));
        else if (stats.startOffset == null || startOffset < stats.startOffset)
            stats.startOffset = startOffset;

        if (stats.endOffset == null || endOffset > stats.endOffset)
            stats.endOffset = endOffset;
    }

    let size = 0;
    for (const [, stats] of fileStats) {
        const offsetSize = (stats.endOffset == null || stats.startOffset == null)
            ? 0
            : Number(BigInt(stats.endOffset) - BigInt(stats.startOffset));
        const tensorsSize = stats.tensorsSize;

        size += Math.max(offsetSize, tensorsSize);
    }

    return size;
}

function calculateTensorSize(tensor: GgufTensorInfo, llama: Llama) {
    const typeSize = llama._bindings.getTypeSizeForGgmlType(tensor.ggmlType);
    const blockSize = llama._bindings.getBlockSizeForGgmlType(tensor.ggmlType);
    const ggmlMaxDims = llama._consts.ggmlMaxDims;

    if (typeSize == null || blockSize == null)
        throw new Error("Invalid type or block size");

    const {ne, nb} = getTensorNeAndNb(tensor, {typeSize, blockSize, ggmlMaxDims});

    if (blockSize === 1) {
        let totalBytes = typeSize;
        for (let i = 0; i < ggmlMaxDims; i++) {
            totalBytes += (ne[i] - 1) * nb[i];
        }

        return totalBytes;
    } else {
        let totalBytes = Math.floor((ne[0] * nb[0]) / blockSize);
        for (let i = 1; i < ggmlMaxDims; i++) {
            totalBytes += (ne[i] - 1) * nb[i];
        }

        return totalBytes;
    }
}

function getTensorNeAndNb(tensor: GgufTensorInfo, {
    typeSize, blockSize, ggmlMaxDims
}: {
    typeSize: number, blockSize: number, ggmlMaxDims: number
}) {
    // number of elements
    // source: `ggml_new_tensor_impl` in `ggml.c`
    const ne = [
        ...tensor.dimensions,
        ...(Array(Math.max(0, ggmlMaxDims - tensor.dimensions.length)).fill(1))
    ].slice(0, ggmlMaxDims);

    // number of bytes
    // source: `ggml_new_tensor_impl` in `ggml.c`
    const nb = [
        typeSize,
        Math.floor(typeSize * (ne[0] / blockSize)),
        ...Array(ggmlMaxDims - 2).fill(0)
    ];
    for (let i = 2; i < ggmlMaxDims; i++) {
        nb[i] = nb[i - 1] * ne[i - 1];
    }

    return {
        ne,
        nb
    };
}

function isInputLayer(layerName: string) {
    const [firstPart] = layerName.split(".");

    if (firstPart == null)
        return false;

    // source: in `llama.cpp`, all tensor names from `LLM_TENSOR_NAMES` where
    // in `llm_tensor_info_mapping` have a mapping to `LLM_TENSOR_LAYER_INPUT`
    switch (firstPart) {
        case "token_embd":
        case "token_embd_norm":
        case "token_types":
        case "position_embd":
            return true;
    }

    return false;
}

function isOutputLayer(layerName: string) {
    const [firstPart, secondPart] = layerName.split(".");

    if (firstPart == null)
        return false;

    // source: in `llama.cpp`, all tensor names from `LLM_TENSOR_NAMES` where
    // in `llm_tensor_info_mapping` have a mapping to `LLM_TENSOR_LAYER_INPUT`
    switch (firstPart) {
        case "output":
        case "output_norm":
        case "cls":
            return true;
    }

    if (secondPart == null)
        return false;

    // source: in `llama.cpp`, all tensor names from `LLM_TENSOR_NAMES` where
    // in `llm_tensor_info_mapping` have a mapping to `LLM_TENSOR_LAYER_INPUT`
    switch (firstPart + "." + secondPart) {
        case "cls.output":
        case "dec.output_norm":
        case "enc.output_norm":
            return true;
    }

    return false;
}

function isMainOutputLayer(layerName: string) {
    const [firstPart] = layerName.split(".");

    return firstPart === "output";
}

function isTokenEmbedLayer(layerName: string) {
    const [firstPart] = layerName.split(".");

    return firstPart === "token_embd";
}

function isGraphRelevantTensor(tensorName: string): boolean {
    return isInputLayer(tensorName) ||
        isOutputLayer(tensorName) ||
        tensorName.startsWith("blk.") ||
        tensorName.startsWith("enc.blk.") ||
        tensorName.startsWith("dec.blk.");
}

function ggmlPad(value: number, padding: number): number {
    return ((value + padding - 1) & ~(padding - 1));
}

function roundUpToMultiple(value: number, multiple: number): number {
    if (multiple <= 1)
        return value;

    return Math.ceil(value / multiple) * multiple;
}

function resolveGraphContextSizeForOverheadEstimation({
    fullAttentionKvSize,
    trainContextSize,
    flashAttention,
    headCount,
    batchSize,
    paddedContextSize,
    sequences
}: {
    fullAttentionKvSize: number,
    trainContextSize: number | undefined,
    flashAttention: boolean,
    headCount: number,
    batchSize: number,
    paddedContextSize: number,
    sequences: number
}) {
    // heuristic coefficients fit to estimate llama.cpp graph-reserve behavior
    const flashAttentionMinContextMultiplier = 0.5;
    const flashAttentionMaxContextMultiplier = 0.78;
    const flashAttentionMinHeadCountForScaling = 4;
    const flashAttentionContextRatioLog2Cap = 2;
    const flashAttentionContextRatioLog2Scale = 0.05;
    const longContextOverflowStartRatio = 1.25;
    const longContextOverflowGrowthScale = 0.1;
    const longContextMaxMultiplierIncrease = 0.4;

    const normalizedTrainContextSize = trainContextSize == null || trainContextSize <= 0
        ? Math.max(1, fullAttentionKvSize)
        : trainContextSize;
    const contextRatio = Math.max(1, fullAttentionKvSize / normalizedTrainContextSize);

    if (flashAttention) {
        const activeGraphTokens = roundUpToMultiple(
            Math.max(1, Math.min(paddedContextSize, batchSize)),
            Math.max(1, sequences)
        );
        const flashContextMultiplierBase =
            flashAttentionMinContextMultiplier + (1 / Math.max(flashAttentionMinHeadCountForScaling, headCount));
        const flashContextMultiplierLongContextAdjustment =
            Math.min(flashAttentionContextRatioLog2Cap, Math.log2(contextRatio)) * flashAttentionContextRatioLog2Scale;
        const flashContextMultiplier = Math.max(
            flashAttentionMinContextMultiplier,
            Math.min(
                flashAttentionMaxContextMultiplier,
                flashContextMultiplierBase + flashContextMultiplierLongContextAdjustment
            )
        );

        return activeGraphTokens * flashContextMultiplier;
    }

    const contextOverflow = Math.max(0, contextRatio - longContextOverflowStartRatio);
    const longContextMultiplier = 1 + Math.min(
        longContextMaxMultiplierIncrease,
        longContextOverflowGrowthScale * contextOverflow * contextOverflow
    );

    return fullAttentionKvSize * longContextMultiplier;
}

function estimateNonFlashAttentionWorkspace({
    trainContextSize,
    fullAttentionKvSize,
    swaKvSize,
    hasSwaAttention,
    maxAttentionLayerKvSize,
    maxAttentionLayerHeadCountKv,
    activeGraphTokens,
    headCount
}: {
    trainContextSize: number | undefined,
    fullAttentionKvSize: number,
    swaKvSize: number,
    hasSwaAttention: boolean,
    maxAttentionLayerKvSize: number,
    maxAttentionLayerHeadCountKv: number,
    activeGraphTokens: number,
    headCount: number
}) {
    const floatBytes = 4; // sizeof(float)
    const strongGqaMaxKvToQHeadRatio = 0.5;
    const minAttentionScoreWorkspaceScale = 0.4;
    const additionalAttentionScoreWorkspaceScale = 0.6;

    if (maxAttentionLayerKvSize <= 0 || activeGraphTokens <= 0 || headCount <= 0)
        return 0;

    const attentionScoresWorkspace = floatBytes * activeGraphTokens * maxAttentionLayerKvSize * headCount;
    const attentionMaskWorkspace = floatBytes * activeGraphTokens * (
        hasSwaAttention
            ? fullAttentionKvSize + swaKvSize
            : maxAttentionLayerKvSize
    );

    if (!hasSwaAttention)
        // source: non-FA reserve path in `llm_graph_context::build_attn_mha` + `build_attn_inp_kq_mask` in `llama-graph.cpp`
        // reserves the full KQ tensor and the matching F32 attention mask for the ubatch-local graph
        return attentionScoresWorkspace + attentionMaskWorkspace;

    // the explicit KQ workspace floor matches the non-FA reserve path well for MHA-like layouts,
    // but it becomes too aggressive for strong GQA / MQA hybrid models where KV heads are much fewer than Q heads
    if (maxAttentionLayerHeadCountKv / headCount < strongGqaMaxKvToQHeadRatio)
        return attentionMaskWorkspace;

    const normalizedTrainContextSize = Math.max(1, trainContextSize ?? maxAttentionLayerKvSize);
    const contextRatio = Math.min(1, Math.max(0, maxAttentionLayerKvSize / normalizedTrainContextSize));
    const attentionScoreWorkspaceScale =
        minAttentionScoreWorkspaceScale + (additionalAttentionScoreWorkspaceScale * contextRatio);

    return (attentionScoresWorkspace * attentionScoreWorkspaceScale) + attentionMaskWorkspace;
}

function isSwaLayerAtIndex(
    architecture: GgufArchitectureType | undefined,
    slidingWindowPattern: number | number[] | undefined,
    layerIndex: number
): boolean {
    if (layerIndex < 0)
        return false;

    if (slidingWindowPattern instanceof Array)
        return Boolean(slidingWindowPattern[layerIndex]);

    const [defaultPattern, denseFirst] = getSwaPatternForArchitecture(architecture);
    const pattern = typeof slidingWindowPattern === "number"
        ? Math.max(0, Math.floor(slidingWindowPattern))
        : defaultPattern;

    if (pattern === 0)
        return true;

    return denseFirst
        ? (layerIndex % pattern !== 0)
        : (layerIndex % pattern < (pattern - 1));
}

function getSwaPatternForArchitecture(architecture?: GgufArchitectureType): [pattern: number, denseFirst: boolean] {
    // source: `llama_model::load_hparams` in `llama-model.cpp` - calls to `hparams.set_swa_pattern`
    switch (architecture) {
        case GgufArchitectureType.llama4:
            return [4, false];
        case GgufArchitectureType.afmoe:
            return [4, false];
        case GgufArchitectureType.modernBert:
            return [3, true];
        case GgufArchitectureType.phi3:
            return [1, false];
        case GgufArchitectureType.plamo3:
            return [8, false];
        case GgufArchitectureType.gemma2:
            return [2, false];
        case GgufArchitectureType.gemma3:
            return [6, false];
        case GgufArchitectureType.gemma3n:
            return [5, false];
        case GgufArchitectureType.gemmaEmbedding:
            return [6, false];
        case GgufArchitectureType.cohere2:
            return [4, false];
        case GgufArchitectureType.olmo2:
            return [4, false];
        case GgufArchitectureType.exaone4:
            return [4, false];
        case GgufArchitectureType.exaoneMoe:
            return [4, false];
        case GgufArchitectureType.gptOss:
            return [2, false];
        case GgufArchitectureType.smallthinker:
            return [4, true];
    }

    return [1, false];
}

function resolveLayerHeadDimension(defaultValue: number, swaValue: number | undefined, isSwaLayer: boolean): number {
    if (isSwaLayer && swaValue != null)
        return swaValue;

    return defaultValue;
}

function doesLayerOwnKvCache(totalLayers: number, layerIndex: number, sharedKvLayers: number | undefined): boolean {
    if (sharedKvLayers == null || sharedKvLayers <= 0)
        return true;

    return layerIndex < Math.max(0, totalLayers - sharedKvLayers);
}

function resolveLayerHeadCountKv(nHeadKv: number | number[], layerIndex: number, nHead: number): number {
    if (typeof nHeadKv === "number")
        return nHeadKv;

    const layerHeadCountKv = nHeadKv[layerIndex];
    if (layerHeadCountKv == null)
        return nHead;

    return layerHeadCountKv;
}

type RecurrentLayersPattern = "none" | "all" |
    {type: "fullAttentionInterval", interval: number} |
    {type: "headCountKvArray", values: number[]} |
    {type: "headCountKvAndFeedForward", headCountKvValues: number[], feedForwardLength: number | number[] | undefined};

function getRecurrentLayersPattern(
    architecture: GgufArchitectureType | undefined,
    architectureMetadata: GgufFileInfo["architectureMetadata"]
): RecurrentLayersPattern {
    const nHeadKv = architectureMetadata?.attention?.head_count_kv;
    const nHeadKvValues: number | number[] | undefined = nHeadKv;
    const feedForwardLength = architectureMetadata?.feed_forward_length as number | number[] | undefined;
    const hasRecurrentHeadCountKvEntry = nHeadKvValues instanceof Array && nHeadKvValues.some((value: number) => value === 0);

    if (architecture === GgufArchitectureType.falconH1)
        // source: `llama_model::load_hparams` in `llama-model.cpp`:
        // `case LLM_ARCH_FALCON_H1` does `std::fill(..., true)` for `recurrent_layer_arr`
        return "all";

    if (architecture === GgufArchitectureType.nemotronH || architecture === GgufArchitectureType.nemotronHMoe) {
        // source: `llama_model::load_hparams` in `llama-model.cpp`:
        // `case LLM_ARCH_NEMOTRON_H / LLM_ARCH_NEMOTRON_H_MOE`:
        // `recurrent_layer_arr[i] = (n_head_kv(i) == 0 && n_ff(i) == 0)`
        if (nHeadKvValues instanceof Array)
            return {
                type: "headCountKvAndFeedForward",
                headCountKvValues: nHeadKvValues,
                feedForwardLength
            };

        if (nHeadKv === 0) {
            if (typeof feedForwardLength === "number")
                return feedForwardLength === 0
                    ? "all"
                    : "none";

            return "none";
        }
    }

    if (
        typeof architectureMetadata?.full_attention_interval === "number" &&
        Number.isFinite(architectureMetadata?.full_attention_interval) &&
        architectureMetadata?.full_attention_interval > 0 &&
        (
            // source: `llama_model::load_hparams` in `llama-model.cpp`
            // `case LLM_ARCH_QWEN3NEXT / LLM_ARCH_QWEN35 / LLM_ARCH_QWEN35MOE`:
            // `hparams.recurrent_layer_arr[i] = ((i + 1) % full_attn_interval != 0)`
            architecture === GgufArchitectureType.qwen3next ||
            architecture === GgufArchitectureType.qwen35 ||
            architecture === GgufArchitectureType.qwen35moe ||
            hasRecurrentHeadCountKvEntry
        )
    )
        return {
            type: "fullAttentionInterval",
            interval: Math.max(1, Math.floor(architectureMetadata?.full_attention_interval))
        };

    if (nHeadKvValues instanceof Array && hasRecurrentHeadCountKvEntry)
        return {
            type: "headCountKvArray",
            values: nHeadKvValues
        };

    return "none";
}

function isLayerRecurrent(pattern: RecurrentLayersPattern, layerIndex: number): boolean {
    if (pattern === "all")
        return true;
    else if (pattern === "none")
        return false;
    else if (pattern.type === "fullAttentionInterval")
        return (layerIndex + 1) % pattern.interval !== 0;
    else if (pattern.type === "headCountKvAndFeedForward")
        return pattern.headCountKvValues[layerIndex] === 0 &&
            resolveLayerFeedForwardLength(pattern.feedForwardLength, layerIndex) === 0;

    return pattern.values[layerIndex] === 0;
}

function resolveLayerFeedForwardLength(feedForwardLength: number | number[] | undefined, layerIndex: number): number {
    if (typeof feedForwardLength === "number")
        return feedForwardLength;
    else if (feedForwardLength instanceof Array)
        return feedForwardLength[layerIndex] ?? 0;

    return 0;
}

export function parseRankingTemplate(template: string | undefined | null): string | undefined {
    if (template == null)
        return undefined;

    return template
        .replaceAll("{query}", "{{query}}")
        .replaceAll("{document}", "{{document}}");
}

export function isRankingTemplateValid(template: string | undefined | null): boolean {
    return template != null && template.includes("{{query}}") && template.includes("{{document}}");
}

export function getDominantTensorType(tensorInfo: GgufTensorInfo[]): GgmlType | undefined {
    const tensorTypes: number[] = [];
    for (const tensor of tensorInfo)
        tensorTypes[tensor.ggmlType] = (
            (tensorTypes[tensor.ggmlType] ?? 0) +
            tensor.dimensions.map(((dim) => Number(dim))).reduce((a, b) => a * b, 1)
        );

    let dominantType: GgmlType | undefined = undefined;
    let maxCount = 0;

    for (const [type, count] of tensorTypes.entries()) {
        if (count > maxCount) {
            maxCount = count;
            dominantType = type;
        }
    }

    return dominantType;
}
